version: '3'

services:
  frontend:
    build:
      context: .
    container_name: "frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    restart: always
    command: npm run start